module.exports = {
    SUCCESS: 'Success',
    ALREADY_EXIST: 'Already exist',
    DOES_NOT_EXIST: 'Does not exist',
    DEFUALT_LIMIT: 10,
    DEFUALT_PAGE: 0,
    INVALID: 'Invalid',
    ALREADY_MAPPED: 'Already mapped',
    NOT_MAPPED: 'Not mapped',
    IMPORT_INVALID_VALUE: 'Invalid client id/carrier id/app id/country id/city id/type',
    NEW_DID_NOT_ALLOWED: 'New DID allocation is not allowed to this carrier',
    NOT_AUTHORISE_TO_CANCEL: 'Re-seller already took action against this request',
    MULTI_DB_NOT_DEFINED: 'Multi DB Access Api not defined ',
    ALREADY_DELETED: 'Already deleted ',
    COMPANY_TYPE_RESELLER:'reseller',
    COMPANY_TYPE_DOMAIN:'domain',
    COMPANY_TYPE_CUSTOMER:'customer',
    PERMISSION_NOT_ALLOWED:'You have no permission',
    PERMISSION_NOT_ALLOWED_RESELLER:'You have no permission for Reseller',
    PERMISSION_NOT_ALLOWED_DOMAIN:'You have no permission for Domain',
    PERMISSION_NOT_ALLOWED_CUSTOMER:'You have no permission for Create Customer',
    FILE_STORAGE_DEFINED: 'File Storage Api not defined ',
    INTERNAL_SERVER_ERROR: 'Internal server error!',
    DOC_NAME : 'doc_name',
    ID_COMPANY : 'id_company',
    DELETED:'Deleted',
    EMAIL:'email',
    COMPANY_STEP_COMPANY_DETAILS:1,
    COMPANY_STEP_CONTACT_DETAILS:2,
    COMPANY_STEP_UPLOAD_DOCUMENTS:3,
    COMPANY_STEP_ADD_ADMINISTRATOR_USER:4,
    COMPANY_STEP_ADMINISTRATOR_PERMISSION:5,
    COMPANY_STEP_SELECT_APPLICATION:6,
    COMPANY_STEP_SET_APPLICATION_PARAMETERS:7,
    COMPANY_STEP_ADD_APPLICATION_USER:8,
    COMPANY_STEP_ASSIGN_USER_PERMISSION:9,
    GRANTED_ADMIN:1,
    GRANTED_APPLICATION:1,
    
}